import { StyleSheet } from "react-native";
import {colors} from '../../Style/vars'

export default StyleSheet.create({
  container:{
    width:'85%',
    height:150,
    marginTop:30,
    borderRadius:20,
    alignItems:'center',
    justifyContent:'space-around',
    backgroundColor:colors.branco,
  },
  containerTitle:{
    width:'90%',
    height:40,
    borderRadius:10,
    alignItems:'center',
    justifyContent:'center',
    backgroundColor:colors.laranja1
  },
  title:{
    fontSize:20,
    fontWeight:'bold',
    color:colors.branco
  },
  containerInfo:{
    flexDirection:"row",
    width:'90%',
    height:70,
  },
  basicDatas:{
    width:'80%',
    height:'100%',
    padding:5,
    paddingRight:10,
    justifyContent:'space-around',
  },
  containerData:{
    width:'100%',
  },
  status:{
    fontSize:18,
    fontWeight:'bold'
  },
  date:{
    fontSize:18
  },
  moreInfo:{
    flex:1,
    padding:5,
    alignItems:'flex-end',
    justifyContent:'flex-end'
  },
  buttonMore:{
    color:colors.laranja1,
    fontSize:18,
    fontWeight:'bold'
  }
})