import { StyleSheet } from "react-native"

export default StyleSheet.create({
	background:{
		flex:1,
		justifyContent:"center",
		alignItems:"center",
		backgroundColor:"#000"
	},
	container:{
		width:350,
		height:500,
		backgroundColor:"rgba(300,300,300,0.25)",
		borderRadius:30,
		alignItems:"center"
	},
	image:{
		height:"35%",
		width:"70%",
	},
	input:{
		height:"45%",
		width:"70%",
		alignItems:"center",
		justifyContent:"space-around"
	},
	iconInput:{
		width:"20%",
		height:"80%",
		borderRightWidth:1,
		borderColor:"#151515",
		justifyContent:"center",
		alignItems:"center"
	},
	txtInput:{
		width:"80%",
		height:"100%",
		paddingHorizontal:10,
		borderTopRightRadius:40,
		borderBottomRightRadius:40,
		fontSize:16,
		fontWeight:"400"
	},
	containerInput:{
		flexDirection:"row",
		width:250,
		height:40,
		borderRadius:40,
		alignItems:"center",
		justifyContent:"space-between",
		backgroundColor:"#D9D9D9"
	},
	containerButton:{
		height:"20%",
		width:"70%",
		alignItems:"center",
		justifyContent:"center"
	},
	buttonLogin:{
		width:200,
		height:40,
		borderRadius:20,
		backgroundColor:"#E43F09",
		justifyContent:"center",
		alignItems:"center"
	},
	buttonTxt:{
		fontSize:16,
		fontWeight:"bold",
		color:"#fff"
	}
})